repos:
  - repo: local
    hooks:
      - id: isort
        stages: [commit]
        name: isort
        entry: isort
        language: system
        exclude: ^migrations/
        types: [python]
        args:
          - --atomic
          - --force-alphabetical-sort-within-sections
          - --remove-redundant-aliases
          - --profile=black
  - repo: local
    hooks:
      - id: black
        stages: [commit]
        name: black
        entry: black
        language: system
        types: [python]
        exclude: ^migrations/
        files: .
        args:
          - --skip-string-normalization
